export enum actionTypes {
  REGISTRATION = '[Auth] REGISTRATION',
  REGISTRATION_SUCCESS = '[Auth] REGISTRATION_SUCCESS',
  REGISTRATION_FAILURE = '[Auth] REGISTRATION_FAILURE',

  LOGIN = '[Auth] LOGIN',
  LOGIN_SUCCESS = '[Auth] LOGIN_SUCCESS',
  LOGIN_FAILURE = '[Auth] LOGIN_FAILURE',

  GET_CURRENT_USER = '[Auth] GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS = '[Auth] GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE = '[Auth] GET_CURRENT_USER_FAILURE',

  UPDATE_CURRENT_USER = '[Auth] UPDATE_CURRENT_USER',
  UPDATE_CURRENT_USER_SUCCESS = '[Auth] UPDATE_CURRENT_USER_SUCCESS',
  UPDATE_CURRENT_USER_FAILURE = '[Auth] UPDATE_CURRENT_USER_FAILURE',

  LOGOUT = '[Auth] LOGOUT'
}
